services:
  neosavage:
    build:
      context: ../src
      dockerfile: ../deploy/Dockerfile
    image: neosavage:latest
    container_name: neosavage
    restart: unless-stopped

    # Environment variables
    env_file:
      - .env

    # Alternative: specify environment variables directly
    # environment:
    #   - DISCORD_TOKEN=${DISCORD_TOKEN}
    #   - NODE_ENV=production

    # Resource limits (optional)
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Health check (optional - requires adding health endpoint)
    # healthcheck:
    #   test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health')"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

    # Network configuration
    networks:
      - neosavage-network

networks:
  neosavage-network:
    driver: bridge
